server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test_task
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 100000

admin:
  email: example@email.com
  password: admin
  username: admin
